@token = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY5OTRhYTdjNmU3Y2M4ZTE1Mjc4OWIwZiIsImVtYWlsIjoiYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3NzEzNTA2NTYsImV4cCI6MTc3MTk1NTQ1Nn0.MnI2bmw7NQM2d-zMWvzh2bCUiwnyX4HYvNtv6SdAB84
###
GET http://localhost:3001/api/user/profile
Authorization: Bearer {{token}}


###
PUT http://localhost:3001/api/user/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "aaaa@gmail.com",
  "profilePic": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFUlEQVR42mNgYGD4z0AEYBxVSF+FAP60AgHtqROlAAAAAElFTkSuQmCC"
}

###
PUT http://localhost:3001/api/user/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "currentPassword": "111111",
  "newPassword": "111111"
}
