###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "TestPassword123!",
  "fullName": "Test User"
}


###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "aaaa@gmail.com",
  "password": "111111"
}